### ISSUE TITLE
Version 3.0?

### ISSUE THREAD

**Issue by ashtuchkin** [parasyte/node-capstone#4]
Right now, `brew install capstone` installs version 3.0, which is incompatible with 2.1.

**Comment by parasyte** [comment]
Yeah, I haven't had a chance to finish the port to 3.0. :( There's a `next` branch where the work was started. It's missing support for one or two architectures.

**Comment by parasyte** [comment]
Fixed in master.

This was a lot more work than I thought it would be. All tests are passing, so I've released [v3.0.0](https://github.com/parasyte/node-capstone/releases/tag/v3.0.0)

Note: I've only tested with node v0.12.x, and the dependencies require a full rebuild: `rm -rf node_modules && npm install`

**Comment by ashtuchkin** [comment]
Thank you!

--
Alexander Shtuchkin
